name: aurasync_engine
description: "AuraSync connects your Android to your PC or Mac for remote control, mirroring and real-time data exchange via USB or local network."

version: 0.1.0

homepage: https://softyes.com.br
repository: https://github.com/AuraSync/aurasync_engine

environment:
  sdk: ^3.8.1
  flutter: ^3.32.8

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0
