name: aurasync_server
description: "AuraSync connects your Android to your PC or Mac for remote control, mirroring and real-time data exchange via USB or local network."

version: 0.1.0

homepage: https://softyes.com.br
repository: https://github.com/AuraSync/aurasync_server

environment:
  sdk: ^3.8.1
  flutter: ^3.32.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
